### PR TITLE
Fix issues in socket/web

### LINKED ISSUE #162: Fix issues in socket/web
Current issues:
* `ws` client only works in Node, should throw instead if `WebSocket` is not detected in the browser environment
* close events are not passed to handlers
* MuWebSocket does not clean up everything after itself

### PR DESCRIPTION
**Pull request by hediyi**
closes #162

### CODE REVIEW

File: src/socket/web/client.ts [hunk 1]
```diff
@@ -28,109 +35,76 @@ export class MuWebSocket implements MuSocket {
...
-                            socket.onclose = () => {
-                                // to avoid closing the socket more than once
-                                removeSocket(socket);
-
-                                for (let i = this._unreliableSockets.length - 1; i >= 0; --i) {
-                                    if (this._unreliableSockets[i] === socket) {
-                                        this._unreliableSockets.splice(i, 1);
-                                    }
+                    // first message indicates whether socket is reliable
+                    if (JSON.parse(event.data).reliable) {
```
Comment (mikolalysenko) [inline src/socket/web/client.ts]: This can throw.  Should wrap it in a try/catch

Comment (mikolalysenko) [reply src/socket/web/client.ts]: Could cause the close() event to fire if the socket never opened.
